name: error_stack_example
description: Learn more here https://nylo.dev.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  nylo_support: ^6.28.5
  error_stack:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  nylo_support:
    path: /Users/anthony/StudioProjects/support

flutter:

  uses-material-design: true